### ISSUE TITLE
Unable to login. Not asking for "Login code", error returned instead

### ISSUE THREAD

**Issue by racalle** [proseltd/Telepathy#52]
Hello, I am using Telepathy in it's last version and Telethon is reported to be the last one too. Last version of python and  so on.

The problem I am facing is that after asking me API and phone information, telepathy stops.

Everything seems normal, and later, when I try to make a query, it sends a message to my phone Telegram but instead of prompt for entering this code it shows an unrecoverable error:

```
root@8826c29fe656:/dataset# telepathy -t durov

      ______     __                 __  __
     /_  __/__  / /__  ____  ____ _/ /_/ /_  __  __
      / / / _ \/ / _ \/ __ \/ __ `/ __/ __ \/ / / /
     / / /  __/ /  __/ /_/ / /_/ / /_/ / / / /_/ /
    /_/  \___/_/\___/ .___/\__,_/\__/_/ /_/\__, /
                   /_/                    /____/
    -- An OSINT toolkit for investigating Telegram chats.
    -- Developed by @jordanwildon | Version 2.0.0.
    

Traceback (most recent call last):
  File "/usr/local/bin/telepathy", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telepathy/telepathy.py", line 177, in cli
    client.sign_in(phone_number)
  File "/usr/local/lib/python3.7/dist-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/auth.py", line 329, in sign_in
    return await self.send_code_request(phone)
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/auth.py", line 460, in send_code_request
    functions.auth.ResendCodeRequest(phone, phone_hash))
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/users.py", line 83, in _call
    result = await future
telethon.errors.rpcerrorlist.SendCodeUnavailableError: Returned when all available options for this type of number were already used (e.g. flash-call, then SMS, then this error might be returned to trigger a second resend) (caused by ResendCodeRequest)`
```

It doesn't make sense to me, and after watching the python code I don't know how to solve this.

**Comment by racalle** [comment]
I am trying another operating system debian based and I have more advance in the installing, but not completely done. I am closing this for now. thx.

**Comment by racalle** [comment]
I am trying another operating system debian based and I have more advance in the installing, but not completely done. I am closing this for now. thx.
